CREATE OR ALTER PROCEDURE ChangeSongIdToBigint
AS
    ALTER TABLE Song
    ALTER COLUMN SongId BIGINT
GO
CREATE OR ALTER PROCEDURE ReverseSongIdToInt
AS
    ALTER TABLE Song
    ALTER COLUMN SongId INT
GO
CREATE OR ALTER PROCEDURE AddVotesFieldToReviews
AS
    ALTER TABLE Review
    ADD UpvotesDownvotes INT
GO
CREATE OR ALTER PROCEDURE RemoveVotesFieldFromReviews
AS
    ALTER TABLE Review
    DROP COLUMN UpvotesDownvotes
GO
