CREATE OR ALTER PROCEDURE ChangeSongIdToBigint
AS
    ALTER TABLE Song
    ALTER COLUMN SongId BIGINT
GO
CREATE OR ALTER PROCEDURE ReverseSongIdToInt
AS
    ALTER TABLE Song
    ALTER COLUMN SongId INT
GO


